CC = g++
flags = -Wall

main: build/main.o build/strings.o build/errors_catch.o
	$(CC) $(flags) -o main.exe build/main.o build/strings.o build/errors_catch.o

build/main.o: main.cpp
	$(CC) -c $(flags) -o build/main.o main.cpp
	
build/strings.o: src/strings.cpp
	$(CC) -c $(flags) -o build/strings.o src/strings.cpp

build/errors_catch.o: src/errors_catch.cpp
	$(CC) -c $(flags) -o build/errors_catch.o src/errors_catch.cpp



run:
	./main

cnr:
	make main
	make run